module.exports = [
  {
    user_id: 1,
    listingAddress: '4411 Iberville St',
    listingCity: 'New Orleans',
    listingState: 'LA',
    listingZipCode: '70119',
    listingTitle: 'Musty basement in a great neighborhood',
    listingDescription: 'Enjoy all that Mid City has to offer. Just blocks from City Park and everyone’s favorite ice cream spot, Angelo Brocato’s, staying here will make you the envy of all New Orleanians. Just know that you’ll be in a musty, funky basement.',
    pets: false,
    ada: true,
    smoking: false,
    roommates: false,
    internet: true,
    privateBath: true
  },
  {
    user_id: 2,
    listingAddress: '2037 S Chippewa St',
    listingCity: 'New Orleans',
    listingState: 'LA',
    listingZipCode: '70130',
    listingTitle: 'An awesome bedroom in a great NOLA neighborhood',
    listingDescription: 'This place is super close to New Orleans’ wonderful Lower Garden District neighborhood. A quick waltz down Jackson will bring you to the famous St. Charles Streetcar line, where you can enjoy a ride through the most beautiful parts of the city. Great restaurants aplenty near this location!',
    pets: false,
    ada: false,
    smoking: false,
    roommates: true,
    internet: true,
    privateBath: false
  },
  {
    user_id: 3,
    listingAddress: '2033 S Chippewa St',
    listingCity: 'New Orleans',
    listingState: 'LA',
    listingZipCode: '70130',
    listingTitle: 'A Lower Garden District Beauty',
    listingDescription: 'Enjoy a huge place in the heart of the Lower Garden District. Super close to several great restaurants and the famous St. Charles Streetcar line. Also just a quick skip from Mardi Gras World and many things that are happening downtown!',
    pets: true,
    ada: false,
    smoking: true,
    roommates: false,
    internet: true,
    privateBath: true
  },
  {
    user_id: 4,
    listingAddress: '2515 Folsom St',
    listingCity: 'San Francisco',
    listingState: 'CA',
    listingZipCode: '94110',
    listingTitle: 'A great place in the hopping Mission District',
    listingDescription: 'Right next door to a great restaurant and wonderful bakery. Take in all that the Mission District has to offer in this luxurious San Francisco spot.',
    pets: false,
    ada: true,
    smoking: false,
    roommates: false,
    internet: false,
    privateBath: true
  },
  {
    user_id: 5,
    listingAddress: '2230 3rd St',
    listingCity: 'San Francisco',
    listingState: 'CA',
    listingZipCode: '94107',
    listingTitle: 'More than a patch of grass in Dogpatch',
    listingDescription: 'Right around the corner from Esprit Park, where dogs are being walked at all hours. Several good restaurants can be found within walking distance, and you’ll be staying just a block away from the trolley line. I have a great desk that would be great for anyone that is travelling for work.',
    pets: true,
    ada: true,
    smoking: false,
    roommates: true,
    internet: true,
    privateBath: false
  }
];