module.exports = [
  {
    firstName: 'Kyle',
    lastName: 'Hellstorm',
    pronouns: 'he/him',
    dob: new Date(1992, 3, 11),
    email: 'khellstorm@gmail.com',
    password: '1234',
    profilePhoto: 'https://images.unsplash.com/photo-1527082395-e939b847da0d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=375&q=80',
    swapCount: 4,
    guestRating: 3.75,
    hostRating: 1.75,
    inviteCount: 2,
    userBio: 'I\'m a dentist, born and raised in New Orleans. I love going out and catching live music shows. Ask me about my favorite po-boy spot. I\'m a pretty neat and organized person and am cool if you want to bring your pets here.',
    hasListing: true,
  },
  {
    firstName: 'Katherine',
    lastName: 'Hughes',
    pronouns: 'she/her',
    dob: new Date(1991, 12, 17),
    email: 'khughes@gmail.com',
    password: '12345678',
    profilePhoto: 'https://images.unsplash.com/photo-1518518873111-6ca469aa4560?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    swapCount: 20,
    guestRating: 4.95,
    hostRating: 4.9,
    inviteCount: 18,
    userBio: 'Hey there! My name is Katherine and live by the Irish Channel if you\'re looking for a good spot with lots of cool locations nearby. I love crawfish boils and watching the Saints on Sundays. I am very organized and keep my house clean (except during Mardi Gras LOL). Feel free to shoot me a message and we can see if we are a good match!',
    hasListing: true,
  },
  {
    firstName: 'Patty',
    lastName: 'Lopez',
    pronouns: 'she/her',
    dob: new Date(1992, 5, 29),
    email: 'pattyklopez@gmail.com',
    password: 'abc123',
    profilePhoto: 'https://images.unsplash.com/photo-1558507652-2d9626c4e67a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80',
    swapCount: 2,
    guestRating: 5,
    hostRating: 4.5,
    inviteCount: 1,
    userBio: 'Hey y\'all!! Recently married and we love going on out of town adventures together. We have two lovely dogs, but they don\'t like to travel, so if you have pets and want to swap rooms, we can totally swaps rooms for free and we\'ll have pre-made pet sitters, too!',
    hasListing: true,
  },
  {
    firstName: 'Shamit',
    lastName: 'Dua',
    pronouns: 'they/them',
    dob: new Date(1993, 4, 21),
    email: 'sdua@gmail.com',
    password: 'pw123',
    profilePhoto: 'https://images.unsplash.com/photo-1523305296308-094f03359092?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=357&q=80',
    swapCount: 3,
    guestRating: 4.67,
    hostRating: 4.67,
    inviteCount: 2,
    userBio: 'Yo waddup, just a Nola native who loves sports and loves to travel. I try to get away from the city when I can so my house stays clean. Promise to keep your place clean too! Hmu if you\'re interested in a swap, and I can always hook you up with Pels tickets.',
    hasListing: true,
  },
  {
    firstName: 'Uday',
    lastName: 'Nandipati',
    pronouns: 'he/him',
    dob: new Date(1992, 10, 25),
    email: 'udaynan@gmail.com',
    password: 'pw1234',
    profilePhoto: 'https://images.unsplash.com/photo-1509933551745-514268e48884?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    swapCount: 0,
    guestRating: 0,
    hostRating: 0,
    inviteCount: 0,
    userBio: 'First of all, don\'t believe anything you hear anyone on this site say about me. I\'m a really chill guy who likes to party, but I keep it classy, too. On the hunt for the perfect collard green sandwich.',
    hasListing: true,
  },
];
