module.exports = [
  {
    first_name: "Kyle",
    last_name: "Hellstrom",
    pronouns: "he/him",
    dob: new Date(1992, 3, 11),
    email: "khellstorm@gmail.com",
    password: "1234",
    profilePhoto: "",
    swapCount: 4,
    guestRating: 3.75,
    hostRating: 1.75,
    inviteCount: 2,
  },
  {
    first_name: "Katherine",
    last_name: "Hughes",
    pronouns: "she/her",
    dob: new Date(1991, 12, 17),
    email: "khughes@gmail.com",
    password: "12345678",
    profilePhoto: "",
    swapCount: 20,
    guestRating: 4.95,
    hostRating: 4.9,
    inviteCount: 18,
  },
  {
    first_name: "Patty",
    last_name: "Lopez",
    pronouns: "she/her",
    dob: new Date(1992, 5, 29),
    email: "pattyklopez@gmail.com",
    password: "abc123",
    profilePhoto: "",
    swapCount: 2,
    guestRating: 5,
    hostRating: 4.5,
    inviteCount: 1,
  },
  {
    first_name: "Shamit",
    last_name: "Dua",
    pronouns: "they/them",
    dob: new Date(1993, 4, 21),
    email: "sdua@gmail.com",
    password: "pw123",
    profilePhoto: "",
    swapCount: 3,
    guestRating: 4.67,
    hostRating: 4.67,
    inviteCount: 2,
  },
  {
    first_name: "Uday",
    last_name: "Nandipati",
    pronouns: "he/him",
    dob: new Date(1992, 10, 25),
    email: "udaynan@gmail.com",
    password: "pw1234",
    profilePhoto: "",
    swapCount: 0,
    guestRating: 0,
    hostRating: 0,
    inviteCount: 0,
  },
];
